---
- hosts: all
  become: true
  vars: 
    document_root: /vagrant

  tasks:
    - name: update apt cache (apt-get update)
      apt: update_cache=yes
    - name: install curl
      apt: name=curl state=present
    
    - include: tasks/node.yml